[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
namegen = "njCkgAPdDfewLAZmWZE1ckRDGAiPTwvWMouGGNCJkiR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
deploy = "anchor build && anchor deploy"
